### ISSUE TITLE
Exclude "\Drupal\Core\Site\Settings class of PHPMD StaticAccess rule

### ISSUE THREAD

**Issue by sbrindle** [axelerant/drupal-quality-checker#13]
Hello,

It is not possible to instantiate or use dependency injection to retrieve a site settings.
So it is a good idea to add an exclusion for this class in the phpmd.xml.dist file

**Comment by hussainweb** [comment]
I agree. I will make this change soon unless you want to submit a PR first. :)

**Comment by sbrindle** [comment]
DONE :)

**Comment by hussainweb** [comment]
Thanks! I merged the PR.
