### ISSUE TITLE
grumpy.txt & happy.txt should be different

### ISSUE THREAD

**Issue by obriat** [axelerant/drupal-quality-checker#18]
The default files are the same which is confusing when using a non color term.

**Comment by hussainweb** [comment]
I can relate. Do you have ideas on what could be a good ASCII art to show a failure?

**Comment by obriat** [comment]
The orignal one from grumphp was clear enough (grumpy/happy lumberjack), but I find it too big and add too much unnecessary scroll. 
Maybe just stick to the essential: a tick or a cross ? Thick enough to be clearly visible

**Comment by hussainweb** [comment]
You're right about it being too big. That's one of the reasons I replaced. I am seeing if there is another artwork I can easily use. If you know of one, please raise a PR.
