### ISSUE TITLE
Not working with Drupal 10

### ISSUE THREAD

**Issue by vishalkhode1** [axelerant/drupal-quality-checker#19]
## Problem Statement:
I'm not able to use it on Drupal 10 project. The problem is coming because of `friendsoftwig/twigcs`
https://github.com/axelerant/drupal-quality-checker/blob/v1.2.0/composer.json#L16

## Possible Solution:
Update the dependencies from:
```"friendsoftwig/twigcs": "^3.2 || ^4.0 || ^5.0",```
to
```"friendsoftwig/twigcs": "^3.2 || ^4.0 || ^5.0 || ^ 6.0",```

**Comment by hussainweb** [comment]
Thanks for the analysis. Is it possible for you to raise a PR? We can drop `^3.2` from the version constraint.

I _think_ GrumPHP shouldn't have a problem with TwigCS 6.0 (even though the [TwigCs.php](https://github.com/phpro/grumphp/blob/master/src/Task/TwigCs.php) was last modified before [6.0 was released](https://github.com/friendsoftwig/twigcs/releases/tag/v6.0.0)). From the release notes, the only relevant BC break is that a few options are now mandatory but GrumPHP is passing them in any case. So, we should be good.

**Comment by vishalkhode1** [comment]
Hi @hussainweb 
Thanks for update. I've created PR #20 for the same. Also, verified and can confirm it's working as expected. Please see below.
<img width="1221" alt="Screenshot 2022-12-13 at 3 36 44 PM" src="https://user-images.githubusercontent.com/81069167/207288708-a15657ce-5538-4f73-8aba-bbbbdcdcd2e9.png">

Please review, merge PR & it would be helpful if you can make a new release.
Thanks.
